// export const USER_API_ENDPOINT ="http://localhost:5001/api/user";
// export const JOB_API_ENDPOINT = "http://localhost:5001/api/job";
// export const APPLICATION_API_ENDPOINT = "http://localhost:5001/api/application";
// export const COMPANY_API_ENDPOINT = "http://localhost:5001/api/company";
export const USER_API_ENDPOINT ="https://career-connect-backend-76e8.onrender.com/api/user";
export const JOB_API_ENDPOINT = "https://career-connect-backend-76e8.onrender.com/api/job";
export const APPLICATION_API_ENDPOINT = "https://career-connect-backend-76e8.onrender.com/api/application";
export const COMPANY_API_ENDPOINT = "https://career-connect-backend-76e8.onrender.com/api/company";
export const SAVEDJOBS_API_ENDPOINT = "https://career-connect-backend-76e8.onrender.com/api/savedjobs";
